export const GAMIFICATION_ASSETS = {
  logo: "/logo-okeganha.png",
  particles: "/particles_glow.png",
  cardBase: "/CARDGLASSBASE.png",
  xpFull: "/barraxp_cheia.png",
  xpEmpty: "/barraxp_vazia.png",
  energyFull: "/barraenergia_cheia.png",
  energyEmpty: "/barraenergia_vazia2.png",
  chest: "/bau.png",
  chestLocked: "/locked-reward.png",
  coin: "/moeda.png",
  crown: "/crown-vip.png",
  rank: "/ranking-badge.png",
  verified: "/verificado.png",
  fire: "/streak-fire.png",
  missionInstagram: "/instagrammissao.png",
  missionTiktok: "/tiktokmissao.png",
  missionYoutube: "/youtube.png",
} as const;
